spring:
  application:
    name: baby-step-app
  datasource:
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASS:postgres}
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${POSTGRES_HOST:localhost}:${POSTGRES_PORT:5432}/${POSTGRES_DBNAME:babystep}
  jpa:
    hibernate:
      ddl-auto: ${HIBERNATE_DDL_AUTO:update}
    show-sql: ${HIBERNATE_SHOW_SQL:true}
